nav:
  - Accueil: index.md
  - Etude de marché: etude/index.md
  - Nos actions:
    - actions/index.md
  - L'Asso:
    - l_asso/index.md
    - Implantation en France: l_asso/implantation.md
    - Nous contacter: l_asso/contact.md
  - Mentions légales:
    - mentions-legales/index.md
    - Politique de confidentialité: mentions-legales/confidentialite.md




site_name: APAFI
copyright: Copyright &copy; 2023 Association de Partage et d'Accompagnement pour la Formation Informatique [APAFI]
extra:
  homepage: /
  generator: false
  social :
    - icon: material/email-outline
      link: /l_asso/contact
      name: Contactez-nous
    #- icon: simple/discord
    #  link: https://discord.gg/#
    #  name: Discord (à venir)
    - icon: fontawesome/brands/github
      link: https://github.com/apafi
      name: GitHub APAFI
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/asso-apafi
      name: LinkedIn APAFI
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/asso.apafi/
      name: Instagram APAFI

theme:
  font:
    text: Nunito
  favicon: assets/images/FI_high_WoB_sf.png
  logo : assets/images/LOGO_high_WoB_sf.png
  features:
  #  - navigation.footer
    - navigation.top
    - navigation.path
    - navigation.expand
    - navigation.instant
    - navigation.tabs
  name: material
  language: fr
  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/lightbulb
      name: Mode sombre

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Mode clair

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
